sources:
  - name: 自由节点1
    url: "https://raw.githubusercontent.com/ripaeod/clash/main/clash.yaml"   # 注意：你写成了 ripaeod
    enabled: true

  - name: 自由节点2
    url: "https://raw.githubusercontent.com/barry-fer/V2ray-Configs/main/All_Configs_Sub.txt"   # 注意：你写成了 barry-fer
    enabled: true
